# Generated by Django 5.0.5 on 2024-07-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='type',
            field=models.CharField(choices=[('8 уроков', '8 уроков'), ('10 уроков', '10 уроков'), ('12 уроков', '12 уроков')], max_length=255),
        ),
    ]
