# Generated by Django 4.2.6 on 2024-08-17 08:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 16, 8, 54, 52, 683787, tzinfo=datetime.timezone.utc)),
        ),
    ]
