# Generated by Django 4.2.6 on 2024-07-31 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_sectioncategory_enrollment_confirmation_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='subscription',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='api.subscription'),
            preserve_default=False,
        ),
    ]
