# Generated by Django 5.0.5 on 2024-08-13 07:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 12, 7, 1, 24, 233279, tzinfo=datetime.timezone.utc)),
        ),
    ]
