# Generated by Django 5.0.5 on 2024-07-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_subscription_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='confirmation_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
