# Generated by Django 5.0.5 on 2024-08-18 08:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_subscription_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 17, 8, 21, 7, 125053, tzinfo=datetime.timezone.utc)),
        ),
    ]
