# Generated by Django 4.2.6 on 2024-07-31 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_enrollment_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
    ]
