# Generated by Django 5.0.5 on 2024-08-07 08:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_subscription_activation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 6, 8, 19, 48, 326882, tzinfo=datetime.timezone.utc)),
        ),
    ]
