# Generated by Django 5.0.5 on 2024-08-26 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_subscription_expiration_date_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_period',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 25, 10, 48, 24, 600433, tzinfo=datetime.timezone.utc)),
        ),
    ]
