# Generated by Django 5.0.5 on 2024-08-26 11:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_payment_payment_period_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='center',
        ),
        migrations.AddField(
            model_name='center',
            name='sections',
            field=models.ManyToManyField(related_name='centers', to='api.section'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 25, 11, 40, 47, 464813, tzinfo=datetime.timezone.utc)),
        ),
    ]
