# Generated by Django 5.0.5 on 2024-08-07 11:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_subscription_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='link',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 6, 11, 30, 50, 567890, tzinfo=datetime.timezone.utc)),
        ),
    ]
