# Generated by Django 5.0.5 on 2024-08-07 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_center_link_alter_subscription_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 6, 12, 6, 42, 174266, tzinfo=datetime.timezone.utc)),
        ),
    ]
