# Generated by Django 5.0.5 on 2024-08-13 06:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_subscription_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 12, 6, 25, 29, 694607, tzinfo=datetime.timezone.utc)),
        ),
    ]
