# Generated by Django 5.0.5 on 2024-07-16 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='IIN',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='birthdate',
        ),
    ]
